### ISSUE TITLE
英文标题职称与名字中间空格大小是否过大？

### ISSUE THREAD

**Issue by liziwl** [Iydon/sustechthesis#15]
![image](https://user-images.githubusercontent.com/23000702/118242085-822ab900-b4cf-11eb-8ae7-f0ea09f5c4c8.png)

如图，感觉不需要 `\quad`，只需要普通空格 @Certseeds

**Comment by Certseeds** [comment]
最新的没这个了

**Comment by Certseeds** [comment]
这一版似乎直接删掉了.
