### ISSUE TITLE
摘要是否应删除年级

### ISSUE THREAD

**Issue by liziwl** [Iydon/sustechthesis#16]
毕业生应无关年级，这里加上年级相当奇怪。

本模板：
![image](https://user-images.githubusercontent.com/23000702/118243177-b9e63080-b4d0-11eb-8821-5c41269f39e9.png)

Word样例：
![image](https://user-images.githubusercontent.com/23000702/118243210-c10d3e80-b4d0-11eb-8664-e68ef581dc98.png)

**Comment by Certseeds** [comment]
![image](https://user-images.githubusercontent.com/51754303/118259483-c9bb4000-b4e3-11eb-935e-367af2ef69bb.png)

**Comment by Certseeds** [comment]
撰写规范是比较老的资料(14年),与较新资料中英文样例(文件里最后更新日期为2019.04.17)比较,采用较新的规范比较好.
