### ISSUE TITLE
封面页是否加入班级

### ISSUE THREAD

**Issue by liziwl** [Iydon/sustechthesis#18]
关于 #14，#13 的更改，由于撰写规定上列出可添加班级，但是中英文样例中并无添加，应再和教工部核实该细节。
@Iydon @Certseeds 

撰写规定：
![image](https://user-images.githubusercontent.com/23000702/118244106-c15a0980-b4d1-11eb-9347-bc04eeb2e7a4.png)

模板样例
![image](https://user-images.githubusercontent.com/23000702/118244043-b1422a00-b4d1-11eb-83fa-17860dc843f9.png)

**Comment by Certseeds** [comment]
令人感叹的是,上图中是"姓名,学号,系别,**年级**,专业,指导教师"

**Comment by Certseeds** [comment]
邮件已发,等待回复中

**Comment by Certseeds** [comment]
回复:撰写规范是比较老的资料(14年),与较新资料中英文封面(17年)比较,采用较新的规范比较好.
而且学号包括了班级信息,其实也不需要填.
