### ISSUE TITLE
系名或者论文题目过长无法换行的问题

### ISSUE THREAD

**Issue by SharonM9911** [iydon/sustechthesis#24]
如题，妮可有些系的名字真的是太长了，所以会出现这种重叠问题，有时候论文题目也很长，除了手动分割到小标题中，有什么自动换行的操作吗？非常感谢
![image](https://user-images.githubusercontent.com/33659961/158768828-94a55a5d-a3b9-4e25-b95c-c34fb9621b8d.png)

**Comment by liziwl** [comment]
> 如题，妮可有些系的名字真的是太长了，所以会出现这种重叠问题，有时候论文题目也很长，除了手动分割到小标题中，有什么自动换行的操作吗？非常感谢 ![image](https://user-images.githubusercontent.com/33659961/158768828-94a55a5d-a3b9-4e25-b95c-c34fb9621b8d.png)

https://github.com/iydon/sustechthesis/pull/26 我实现了一个版本，但是有些细节需要确认一下。你也可以看看。

**Comment by SharonM9911** [comment]
好的，我看一下，非常感谢！

**Comment by SharonM9911** [comment]
尝试用了下您的代码，中英文的题目过长问题依旧是没有很好的分行，没找到代码的问题，因此再次提交上来看看您有什么新的发现。祝好！
![chn](https://user-images.githubusercontent.com/33659961/158826999-8a182e93-e1fb-4aa2-8452-6a08584549e3.png)
![en](https://user-images.githubusercontent.com/33659961/158827022-bdb7b14d-1501-4a69-add7-67db5eeea34f.png)

**Comment by liziwl** [comment]
info.tex 那里需要手动换行

**Comment by SharonM9911** [comment]
啊是我傻了，对不起，已经改好了，非常感谢！
