### ISSUE TITLE
英文版的一些字段没有适配

### ISSUE THREAD

**Issue by liziwl** [iydon/sustechthesis#29]
requested by @EricLee543 
- [x] 图表前缀

**Comment by Zoom1111** [comment]
可以在sustechthsis.cls中修改成英文

**Comment by EricLee543** [comment]
对于图标前缀问题已自行修改。还发现了另外一个问题：若将 scheme=chinese 改成plain，英文行距不正确（肉眼看上去是1倍，Chinese模式的英文行距是1.5倍）

**Comment by Zoom1111** [comment]
英文的行间距问题如何解决？我没注意这一点

**Comment by liziwl** [comment]
> 对于图标前缀问题已自行修改。还发现了另外一个问题：若将 scheme=chinese 改成plain，英文行距不正确（肉眼看上去是1倍，Chinese模式的英文行距是1.5倍）

所以不管是中文写还是英文写行距都是1.5倍？

**Comment by EricLee543** [comment]
> 

看毕业论文的要求似乎是这样的，并没有针对英文和中文进行说明。原文是“要求1.5倍行距”，我个人认为应该是要中英文都保持1.5倍行距
