### ISSUE TITLE
2022年机械系毕设模板修改

### ISSUE THREAD

**Issue by Cosmo991119** [iydon/sustechthesis#31]
[sustechthesis.txt](https://github.com/iydon/sustechthesis/files/8555756/sustechthesis.txt)

对照2022年机械系毕设要求word文档修改。使用时请自行更改尾缀。

**Comment by liziwl** [comment]
能提供一下要求的源文件吗？

**Comment by SharonM9911** [comment]
[20220423南科大毕设论文格式样例.docx](https://github.com/iydon/sustechthesis/files/8556208/20220423.docx)

**Comment by SharonM9911** [comment]
这个是我们系里发的

**Comment by liziwl** [comment]
> [20220423南科大毕设论文格式样例.docx](https://github.com/iydon/sustechthesis/files/8556208/20220423.docx)

可见改动：
* 承诺书无需页码
* 摘要和目录使用罗马数字页码，从1开始
* 正文使用阿拉伯数字页码，从1开始

封面改动还需确认中英文是否同步，例如页顶部的元数据信息。

**Comment by Cosmo991119** [comment]
> [20220423南科大毕设论文格式样例.docx](https://github.com/iydon/sustechthesis/files/8556208/20220423.docx)

你这个和系里毕设群那个稍微有点不一样。毕设群4/3号那版要求承诺书起带罗马数字编码。顺便，你改引用格式了么，想嫖。

**Comment by Cosmo991119** [comment]
> [20220423南科大毕设论文格式样例.docx](https://github.com/iydon/sustechthesis/files/8556208/20220423.docx)
[南科大毕设论文格式样例.docx](https://github.com/iydon/sustechthesis/files/8562744/default.docx)
4/3号版

**Comment by SharonM9911** [comment]
> 

最新格式是从摘要开始的吧，233333，引用我还没看，先凑合着
