### ISSUE TITLE
Bug: 参考文献、附录、致谢的链接跳转位置错误

### ISSUE THREAD

**Issue by XDZhelheim** [iydon/sustechthesis#32]
学长好！我在模板中发现了一个链接跳转位置错误的问题，以下为详细说明。

## 问题说明

参考文献的链接跳转到了最后一个 section，附录跳转到了参考文献，致谢跳转到了附录的结尾（或者致谢上方某个位置？）。 

通过目录跳转或者 PDF 阅读器的边栏跳转均可复现错误。

## 测试环境

1. GitHub Release v1.3.2 中直接下载的 main.pdf
2. 最新开发版编译 - Windows 10 - `TeX Live 2020`
3. 最新开发版编译 - macOS 12 - `MacTex 2021`

以上三种情况均存在跳转错误问题。麻烦学长确认下是否存在 bug，还是我的个人环境有问题。

## 解决方案

添加 `\phantomsection`，例如致谢：
```
\newcommand{\致谢}{
  \phantomsection % <---------- added
  \addcontentsline{toc}{section}{致谢}
  \sectionmark{致谢}
  \section*{\centerline{致谢}}
}
```

如果这个方案可行，我可以提交一个 PR。

https://github.com/XDZhelheim/sustechthesis/commit/31ad79ff0a4d9258bd07afa25305c02ae9e7d648

**Comment by Jimmy-7664** [comment]
我遇见了同样的bug，目录的跳转存在问题

**Comment by liziwl** [comment]
@XDZhelheim 提PR吧，是有这个问题
