### ISSUE TITLE
中文论文的et al.更换为“等人”

### ISSUE THREAD

**Issue by wateryloo** [iydon/sustechthesis#33]
您好！

我在写论文时发现在中文环境下，\citeauthor{}的输出也是et al.，但是在中文环境下可能使用“和”以及“等人”更好。参考[这个链接](https://github.com/mohuangrui/ucasthesis/issues/296)可更改为“等人”，请问维护者们能否将此功能加入？类似的代码如下。

```latex
\DefineBibliographyStrings{english}{
        andincite         = {和},
        andincitecn       = {和},
        andothersincitecn = {等人},
        andothersincite   = {等人},%adddot才能避开标点追踪
}
```

谢谢！

**Comment by liziwl** [comment]
应该是可以加入的，待测试下兼容性就合并。

**Comment by liziwl** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/23000702/169973326-cf715c7c-2e78-42ab-b6a7-8f17251261b9.png">

实现效果
