### ISSUE TITLE
关于页码如何调整的疑问

### ISSUE THREAD

**Issue by 1371131436** [iydon/sustechthesis#39]
![image](https://user-images.githubusercontent.com/58131846/228463970-e92b6111-57a7-4cd7-a82b-5db33dc841fa.png)
你好，今年的论文撰写规范中要求页码使用阿拉伯数字，目前模版从摘要开始的三页是罗马数字页码，想问该如何调整呢

**Comment by liziwl** [comment]
https://github.com/iydon/sustechthesis/blob/ca56a8b4d0a10da29fea2f953d0e2eba5a1b217d/sustechthesis.cls#LL194-L201C2 

`\前序格式化` 里面
` \pagenumbering{Roman}` 改成 `\pagenumbering{arabic}`

**Comment by 1371131436** [comment]
已解决，非常感谢。
