### ISSUE TITLE
英文关键字显示问题

### ISSUE THREAD

**Issue by Xilesun** [Iydon/sustechthesis#4]
英文关键字有多个时，用逗号分割，且逗号后面有一个空格的时候，只能显示第一个关键字。

`\begin{英文摘要}{keyword1,keyword2}` 显示结果为 `keyword1,keyword2`

`\begin{英文摘要}{keyword1, keyword2}` 仅显示 `keyword1`

希望在保持逗号后面带空格的格式的情况下能正常显示多个关键字。

另：
- 最好列举一下编译所需的所有宏包，避免报错之后逐个安装
- 好像字体和mac不是很兼容，加上 `fontset=mac` 之后才正常，最好可以提示一下

**Comment by Certseeds** [comment]
#11 中已修复这个问题,其中将英文摘要默认分隔符设置为英文逗号+标点
字体已通过submodule方式跨平台统一,应该没问题了.

**Comment by liziwl** [comment]
已经修复
