### ISSUE TITLE
关于参考文献格式的问题

### ISSUE THREAD

**Issue by 1371131436** [iydon/sustechthesis#41]
![NQFM27QDTR@%0QY~6@6GQVF](https://user-images.githubusercontent.com/58131846/236690641-5e182831-d46d-420b-aff9-2481de144cf3.png)
![%R29C)7)6(`G80Y38YM@EHT](https://user-images.githubusercontent.com/58131846/236690652-6910f15b-8d5b-4250-a16a-6526d4a1266d.png)
你好，当ref.bib中引用的文献是inproceedings类型时，文章名和会议名之间不是用 "." 隔开的而是用"//"隔开的，和撰写规范不太一样，请问有修改的方法吗

**Comment by liziwl** [comment]
![image](https://github.com/iydon/sustechthesis/assets/23000702/26a9b7f0-a34e-4392-b9e2-b99cc7f67c12)

config/preamble.tex 文件中可以这么设置

\usepackage[style=gb7714-2015,gbpunctin=false]{biblatex}

**Comment by liziwl** [comment]
其他可以参考：https://ctan.math.illinois.edu/macros/latex/contrib/biblatex-contrib/biblatex-gb7714-2015/biblatex-gb7714-2015.pdf

**Comment by 1371131436** [comment]
解决了，非常感谢！
