### ISSUE TITLE
bug: 三线表样式

### ISSUE THREAD

**Issue by Zhou-Yicheng** [iydon/sustechthesis#42]
> 3. 表题用五号宋体加黑，表格内中文用五号宋体，英文用五号Times New Roman字体

实际表题符合规范，表内中文为小四宋体，英文为小四Times New Roman

**Comment by liziwl** [comment]
确实有这个问题，我还没看到比较好的方式修。临时的办法是在table环境中的第一行加上 `\五号` 的命令。

**Comment by liziwl** [comment]
该问题已修复
