### ISSUE TITLE
英文模式下怎么把默认中文小标题转换为英文

### ISSUE THREAD

**Issue by ChyenGCY** [iydon/sustechthesis#49]
你好，想问一下在language=english设定好之后，原来的接口比如\摘要标题，\参考文献，\附录，\致谢都还默认输出是中文，想问下这些需要怎么样才能更改为英文

**Comment by liziwl** [comment]
![image](https://github.com/iydon/sustechthesis/assets/23000702/f4f821fb-e2e3-4c36-b1a5-21dfc5885af9)
英文版摘要标题不需要输出指导老师

**Comment by liziwl** [comment]
试试这个分支的代码，https://github.com/iydon/sustechthesis/tree/feat/english-v1

**Comment by ChyenGCY** [comment]
好的谢谢，另外似乎参考文献的行距并不是1.5倍行距
![image](https://github.com/iydon/sustechthesis/assets/87359692/acae88e3-6501-4829-9c2b-23338502269e)
![image](https://github.com/iydon/sustechthesis/assets/87359692/9c1cd319-b9c2-4f75-8cb5-a769f895c871)

**Comment by liziwl** [comment]
设定确实是1.5倍，可以叠图看看吗。

**Comment by ChyenGCY** [comment]
<img width="1493" alt="image" src="https://github.com/iydon/sustechthesis/assets/87359692/b59df9fe-c5f7-4883-bb53-ea358d9fc332">
一个放大大小截图的，仔细看确实行距有区别
