### ISSUE TITLE
英文封面显示 “undergraduate thesis” 字体有点奇怪

### ISSUE THREAD

**Issue by liziwl** [Iydon/sustechthesis#9]
![image](https://user-images.githubusercontent.com/23000702/117523781-afb5c500-afec-11eb-93e9-ec8555be825e.png)

字体看起不是很像 Times New Rome

这是Word 中的渲染
![image](https://user-images.githubusercontent.com/23000702/117523851-04594000-afed-11eb-8635-9e7aa0ba4cd2.png)

**Comment by Certseeds** [comment]
最新版的main.pdf在[github actions的artifacts](https://github.com/Iydon/sustechthesis/actions/runs/820447565)这个页面上,标题截图如下
![image](https://user-images.githubusercontent.com/51754303/117525205-b7c53300-aff3-11eb-8eaa-b196235b3f68.png)

**Comment by liziwl** [comment]
> 最新版的main.pdf在[github actions的artifacts](https://github.com/Iydon/sustechthesis/actions/runs/820447565)这个页面上,标题截图如下
> ![image](https://user-images.githubusercontent.com/51754303/117525205-b7c53300-aff3-11eb-8eaa-b196235b3f68.png)
> 
> @liziwl

原来如此。
